const BASE_URL='http://www.11lang.cn/api/'
export const GET_BARRAGE=BASE_URL+'getBarrage'
export const ADD_BARRAGE=BASE_URL+'addBarrage'
export const GET_DAILY=BASE_URL+'getDaily'
export const ADD_DAILY=BASE_URL+'addDaily'
export const DELETE_DAILY=BASE_URL+'deleteDaily'
export const ADD_COMMENTS=BASE_URL+'addComments'